name: release

on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EXT_NAME: Cloudflare
    steps:
      - name: Setup PHP 7.4
          run: sudo update-alternatives --set php /usr/bin/php7.4
      - name: Extract branch name
        id: extract_branch
        run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/tags/})"
      - uses: actions/checkout@v2
        with:
          path: ./${{ env.EXT_NAME }}
      - name: Install dependencies
        run: composer install --no-dev
        working-directory: ./${{ env.EXT_NAME }}

      - name: tar.gz
        run: tar -zcvf ${{ env.EXT_NAME }}-${{steps.extract_branch.outputs.tag}}.tar.gz ${{ env.EXT_NAME }}

      - name: Upload Release
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./${{ env.EXT_NAME }}-${{steps.extract_branch.outputs.tag}}.tar.gz
          asset_name: ${{ env.EXT_NAME }}-${{steps.extract_branch.outputs.tag}}.tar.gz
          asset_content_type: application/gzip
